### ISSUE TITLE
Consider using `mussel`?

### ISSUE THREAD

**Issue by firasuke** [dslm4515/Forked-LFS#3]
Hey there @dslm4515,

I've been following your work ever since `Musl-LFS`, and I was wondering did you consider using [`mussel`](https://github.com/firasuke/mussel) for the toolchain part?

I saw that you're spending a lot of your time trying to get the toolchain to build and work, perhaps try using [`mussel`](https://github.com/firasuke/mussel)?

As you may know, glaucus uses an integrated version of [`mussel`](https://github.com/firasuke/mussel), and a new project called [`qLinux from scratch`](https://qlinux.qware.org/doku.php/qlinux/1.0/crosstools) is also using it with instructions on how to integrate it with the rest of the system.

Also consider reading mussel's [README](https://github.com/firasuke/mussel/blob/master/README.md) and [DOCUMENTATION](https://github.com/firasuke/mussel/blob/master/DOCUMENTATION.md) files as it may help improve the way you're building your toolchains.

Best of luck!

**Comment by dslm4515** [comment]
I was under the impression that mussel isn't a 'sandboxed' toolchain... I wanted a toolchain that was portable across the same cpu architecture.

It's been sometime, so I will see if I can build MLFS with mussel.

**Comment by dslm4515** [comment]
I also looked at qLinux that you mentioned...WOW. That does reduce the "book" a lot!

Plus, using mussel would then keep the toolchain development separate from MLFS!
